version: "3.8"

services:
  connexion:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./connexion:/connexion
    command: >
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=akhikachmoney
      - POSTGRES_USER=moussa
      - POSTGRES_PASSWORD=passer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
